### ISSUE TITLE
depth map on custom dataset

### ISSUE THREAD

**Issue by zhangkangkai** [IDEA-Research/3D-deformable-attention#2]
Great work.  How to obtain depth map if I want to train on custom dataset and only have multi-view images without lidar?

**Comment by LHY-HongyangLi** [comment]
If you have the annotation of 3D bounding box, you can generate the depth map as in OA-BEV. 

However, without lidar information, there is no way to check if the annotations are correct, resulting in the unreliable depth map and also the final training target.

**Comment by zhangkangkai** [comment]
@LHY-HongyangLi , Thank you very much. I'll try to see if this is feasible.

**Comment by LHY-HongyangLi** [comment]
Good luck! I'll close this issue, if you have any questions feel free to reopen it.
