### ISSUE TITLE
How to utilize BEVFormer-DFA3D GT?

### ISSUE THREAD

**Issue by Yzichen** [IDEA-Research/3D-deformable-attention#3]
The lidar projection is sparse in the image, so when using GT depth map, how do you handle pixels without gt depth?  If you use small resolution images, the blank area can be set to the furthest distance. But if using a large resolution image where many foreground pixels are also blank, how to handle .

**Comment by LHY-HongyangLi** [comment]
Hi @Yzichen, I'm sorry for my late reply. 
As in https://github.com/IDEA-Research/3D-deformable-attention/blob/daba29a22d9430d4d2bf8330db9e2b7c8fed51cf/BEVFormer_DFA3D/projects/mmdet3d_plugin/bevformer/dense_heads/depth_head.py#L403, we simply treat the pixels that has no lidar points projected on as empty, where the depth distribution is all zero. 
Hope this response can address your confusion.

**Comment by LHY-HongyangLi** [comment]
> Hi @Yzichen, I'm sorry for my late reply. As in
> 
> https://github.com/IDEA-Research/3D-deformable-attention/blob/daba29a22d9430d4d2bf8330db9e2b7c8fed51cf/BEVFormer_DFA3D/projects/mmdet3d_plugin/bevformer/dense_heads/depth_head.py#L403
> 
> , we simply treat the pixels that has no lidar points projected on as empty, where the depth distribution is all zero.
> Hope this response can address your confusion.

I think your concern about the large resolution is really reasonable! In our experiments, the resolutions of feature maps are small enough, and most of the pixels can get their meaningful depth value.

**Comment by Yzichen** [comment]
Okay, I got it. Thanks for your clear explanation.
