### ISSUE TITLE
Train on Single-View / Few-View Dataset

### ISSUE THREAD

**Issue by Cindy0725** [IDEA-Research/3D-deformable-attention#4]
Hi, great work done! I am new to image-based 3D object detection and I want to ask some questions about this paper. 
Since I am working on single-view dataset, I am wondering whether it's possible to modify the code to train on single-view dataset? Can I still take the outer-product of depth distrbution and 2D feature map, then use DFA3D to lift it, just skip the aggregation between different views (as shown by the following equation)? 
![1694687258522](https://github.com/IDEA-Research/3D-deformable-attention/assets/38576019/ebf36d22-2354-45d2-b52c-d7afd7995736)
Btw, I am wondering whether the outer-product operation is useful for indoor environment. Does it only work for outdoor BEV feature lifting? 
Thank you very much! Looking forward to your reply.

**Comment by LHY-HongyangLi** [comment]
Hi @Cindy0725, thanks for your attention.
1. DFA3D has no limitation to the number of views. Actually, as in the following line of code, the dimension of views is mixed into the dimension of batch.
https://github.com/IDEA-Research/3D-deformable-attention/blob/daba29a22d9430d4d2bf8330db9e2b7c8fed51cf/BEVFormer_DFA3D/projects/mmdet3d_plugin/bevformer/modules/spatial_cross_attention.py#L733
2. DFA3D's superiority was verified on BEV-based detection by us, but we think DFA3D should be helpful as long as you want to do 3D task with only 2D input. Feel free to open an issue to discuss the problems you meet when you implementing DFA3D on the task you are interested in. Good luck!

**Comment by LHY-HongyangLi** [comment]
I'll close this issue. If you have any other questions about integrating DFA3D into your own project, feel free to reopen it.
