### ISSUE TITLE
Can DFA3D module be exported to TensorRT?

### ISSUE THREAD

**Issue by QingXIA233** [IDEA-Research/3D-deformable-attention#5]
Hello, really enlightening works! I wonder whether it's possible to convert your DFA3D to onnx and TensorRT models. Currently, TensorRT has supported MultiScaleDeformableAttention 2D, did you consider the deployment of DFA3D or should I write TensorRT plugin for it by myself?

**Comment by QingXIA233** [comment]
BTW, If I click the config link of DFA3D-based BevFormers in the model zoo in README page:
![image](https://github.com/IDEA-Research/3D-deformable-attention/assets/64100948/36e03d92-5cf4-4b98-a07d-24cc4820ecf1)
 I got this error:
![image](https://github.com/IDEA-Research/3D-deformable-attention/assets/64100948/472c233f-0426-4cca-8b42-a5c8677ac459)
Perhaps there're some errors?

**Comment by LHY-HongyangLi** [comment]
> Hello, really enlightening works! I wonder whether it's possible to convert your DFA3D to onnx and TensorRT models. Currently, TensorRT has supported MultiScaleDeformableAttention 2D, did you consider the deployment of DFA3D or should I write TensorRT plugin for it by myself?

Hi @QingXIA233 , I'm sorry for my late reply.
    Sure, we would like to implement DFA3D to onnx and TensorRT to convenient the users in AutoDriving community. However, recently I'm busy with something others, and can not pay attention to the implementation.  We welcome the contribution of the community users.

**Comment by LHY-HongyangLi** [comment]
> BTW, If I click the config link of DFA3D-based BevFormers in the model zoo in README page:
> ![image](https://user-images.githubusercontent.com/64100948/268580033-36e03d92-5cf4-4b98-a07d-24cc4820ecf1.png)
> I got this error:
> ![image](https://user-images.githubusercontent.com/64100948/268579791-472c233f-0426-4cca-8b42-a5c8677ac459.png)
> Perhaps there're some errors?

I'm sorry for our mistake 😂. We have fixed this bug, thank you very much!

**Comment by QingXIA233** [comment]
> > Hello, really enlightening works! I wonder whether it's possible to convert your DFA3D to onnx and TensorRT models. Currently, TensorRT has supported MultiScaleDeformableAttention 2D, did you consider the deployment of DFA3D or should I write TensorRT plugin for it by myself?
> 
> Hi @QingXIA233 , I'm sorry for my late reply. Sure, we would like to implement DFA3D to onnx and TensorRT to convenient the users in AutoDriving community. However, recently I'm busy with something others, and can not pay attention to the implementation. We welcome the contribution of the community users.

@LHY-HongyangLi Thank you for the reply. I understand your position. I'm currently trying to convert DFA3D to onnx and trt. BTW, I see that you have the plan of releasing "Format and release the code of "preparing depth map"", may I ask when this will be completed, or could you please give me some hints of generation depth map gt? Currently, I generate my depth gt by using lidar points, intrinsic parameters and mei projection, I also set depth_map[depth_map > 60] = 0. The shape is (B, N, H, W), where N stands for the camera num, (H, W) is the height and width of the input images. I wonder whether you performed other processes on depth map gt or what I did is ok. Thanks advance for your help.

Best regards

**Comment by LHY-HongyangLi** [comment]
Hi @QingXIA233 , 
I'm grateful for your attention and welcome your contribution!
I'm recently busy with something others, so "Format and release the code of "preparing depth map" may be delayed until next month. You can refer to SOLOFusion or BEVDepth for the generating of depth map. Good luck!

**Comment by LHY-HongyangLi** [comment]
I'll close this issue, if you have any further questions, feel free to reopen it.
