### ISSUE TITLE
Version of packages in the environment 

### ISSUE THREAD

**Issue by Cindy0725** [IDEA-Research/3D-deformable-attention#6]
Hi, it's great work! 
I am trying to reproduce and modify the code to train on another dataset. However, I am encountering some bugs when running the code with the latest version mmdet3d&mmdet&mmcv package. 
3D deformable attention uses "DetrTransformerDecoderLayer" in the model, but it seems that this module is not available in mmdet  > 3.0.0rc5. The mmdetection3d official documentation says that current detr3d code can't work with mmdet > 3.0.0rc5. 
Since there is much difference between mmdet3d-1x and mmdet3d-0x, I would like to ask about the detailed environment of your project, e.g the version of each package, which would be much more convenient to reproduce and modify the code. 
Thank you very much! Looking forward to your kind reply!

**Comment by LHY-HongyangLi** [comment]
Hi @Cindy0725 , thanks for your attention. The version of mmdet3d in my environment is 0.17.1

**Comment by Cindy0725** [comment]
> Hi @Cindy0725 , thanks for your attention. The version of mmdet3d in my environment is 0.17.1

Hi @LHY-HongyangLi , thank you very much for your reply! I also want to ask about the version of mmcv/mmcv-full, mmdet and mmseg since I encounter problems making them compatible with each other. 
I think the problem may be due to my pytorch and cuda version. I have a higher torch and cuda version than you, so I can't install low version mmdet, mmcv and mmdet3d. I am trying to use docker to solve this problem, will you release a docker image of your environment in the future?
Thanks again for your help!

**Comment by LHY-HongyangLi** [comment]
OK, here are the packages and their corresponding versions:
```
mmcv-full                 1.4.0                    
mmdet                     2.14.0                   
mmdet3d                   0.17.1                  
mmsegmentation            0.14.1           
```
I'm sorry, we have no plan to release a docker image right now, but we will consider including it in our todo list, thank you for your suggestion!

**Comment by Cindy0725** [comment]
> OK, here are the packages and their corresponding versions:
> 
> ```
> mmcv-full                 1.4.0                    
> mmdet                     2.14.0                   
> mmdet3d                   0.17.1                  
> mmsegmentation            0.14.1           
> ```
> 
> I'm sorry, we have no plan to release a docker image right now, but we will consider including it in our todo list, thank you for your suggestion!

Okay, thank you very much! I will try to pull a pytorch image with the same version cuda as you. Have a nice day.

**Comment by LHY-HongyangLi** [comment]
Thank you!  I'll close this issue. If you have any further questions, feel free to reopen it.
